set(CPU_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cpu)
set(SD_CARD_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/sd_card)

add_subdirectory(cpu)
add_subdirectory(sd_card)

set(RTL_SOURCES ${CPU_SOURCES} ${SD_CARD_SOURCES})

set(CPU_SOURCE_DIR ${CPU_SOURCE_DIR} PARENT_SCOPE)
set(SD_CARD_SOURCE_DIR ${SD_CARD_SOURCE_DIR} PARENT_SCOPE)
set(RTL_SOURCES ${RTL_SOURCES} PARENT_SCOPE)
