set(CPU_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cpu)
set(SD_CARD_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/sd_card)
set(CARTRIDGE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cartridge)

add_subdirectory(cpu)
add_subdirectory(sd_card)
add_subdirectory(cartridge)

set(RTL_SOURCES ${CPU_SOURCES} ${SD_CARD_SOURCES} ${CARTRIDGE_SOURCES})

set(CPU_SOURCE_DIR ${CPU_SOURCE_DIR} PARENT_SCOPE)
set(SD_CARD_SOURCE_DIR ${SD_CARD_SOURCE_DIR} PARENT_SCOPE)
set(CARTRIDGE_SOURCE_DIR ${CARTRIDGE_SOURCE_DIR} PARENT_SCOPE)
set(RTL_SOURCES ${RTL_SOURCES} PARENT_SCOPE)
