# Prints a summary of the testbench results recorded by run_tb.cmake.
#
# Inputs: RESULT_DIR

string(ASCII 27 ESC)
if(DEFINED ENV{NO_COLOR})
    set(GREEN "")
    set(RED "")
    set(BOLD "")
    set(RST "")
else()
    set(GREEN "${ESC}[32m")
    set(RED "${ESC}[31m")
    set(BOLD "${ESC}[1m")
    set(RST "${ESC}[0m")
endif()

file(GLOB STATUS_FILES "${RESULT_DIR}/*.status")
list(SORT STATUS_FILES)

set(PASSED 0)
set(FAILED "")
foreach(F IN LISTS STATUS_FILES)
    get_filename_component(NAME "${F}" NAME_WE)
    file(STRINGS "${F}" RES LIMIT_COUNT 1)
    if(RES STREQUAL "PASS")
        math(EXPR PASSED "${PASSED} + 1")
    else()
        list(APPEND FAILED "${NAME}")
    endif()
endforeach()

list(LENGTH STATUS_FILES TOTAL)
list(LENGTH FAILED N_FAILED)

message("")
message("${BOLD}==== Testbench summary ====${RST}")
if(TOTAL EQUAL 0)
    message("No results found. Run the sim_* targets first.")
    return()
endif()
message("${GREEN}passed: ${PASSED}${RST} / ${TOTAL}")
if(N_FAILED GREATER 0)
    message("${RED}failed: ${N_FAILED}${RST}")
    foreach(NAME IN LISTS FAILED)
        message("  ${RED}x${RST} ${NAME}")
    endforeach()
    message(FATAL_ERROR "")
endif()
